#!/bin/bash
# .openshift/action_hooks/deploy
# This script will be executed after the code is built and deployed,
# before the application is started.

for CONFIG_FILE in diaspora.yml database.yml ; do
  echo -n "Checking for $OPENSHIFT_DATA_DIR/$CONFIG_FILE ..."
  if [[ -r $OPENSHIFT_DATA_DIR/$CONFIG_FILE ]]; then
    echo " found, copying to $OPENSHIFT_REPO_DIR/config/$CONFIG_FILE"
    cp $OPENSHIFT_DATA_DIR/$CONFIG_FILE $OPENSHIFT_REPO_DIR/config/
  else
    echo "not found -- your application won't boot correctly!"
  fi
done

echo -n "Checking for $OPENSHIFT_DATA_DIR/splash.html.haml ..."
if [[ -r $OPENSHIFT_DATA_DIR/splash.html.haml ]]; then
  echo "found, copying to $OPENSHIFT_REPO_DIR/app/views/home/_show.html.haml"
  cp $OPENSHIFT_DATA_DIR/splash.html.haml $OPENSHIFT_REPO_DIR/app/views/home/_show.html.haml
else
  echo "not found -- the default splash screen will be used"
fi
