#!/bin/bash
# .openshift/action_hooks/deploy
# This script will be executed after the code is built and deployed,
# before the application is started.

for CONFIG_FILE in diaspora.yml database.yml ; do
  if [[ -r $CONFIG_FILE ]]; then
    echo "Copying $CONFIG_FILE ..."
    cp $OPENSHIFT_DATA_DIR/$CONFIG_FILE $OPENSHIFT_REPO_DIR/config/
  else
    echo "Cannot find the $CONFIG_FILE -- your application won't boot correctly!"
  fi
done

cp $OPENSHIFT_DATA_DIR/splash.html.haml $OPENSHIFT_REPO_DIR/app/views/home/_show.html.haml
