#!/bin/bash
# This script will be executed after the code is built and deployed,
# before the application is started.

for CONFIG_FILE in diaspora.yml database.yml ; do
  echo -n "Checking for $OPENSHIFT_DATA_DIR/$CONFIG_FILE ... "
  if [[ -r $OPENSHIFT_DATA_DIR/$CONFIG_FILE ]]; then
    echo " found, copying to $OPENSHIFT_REPO_DIR/config/$CONFIG_FILE"
    cp $OPENSHIFT_DATA_DIR/$CONFIG_FILE $OPENSHIFT_REPO_DIR/config/
  else
    echo "not found -- your application won't boot correctly!"
  fi
done

echo -n "Checking for $OPENSHIFT_DATA_DIR/splash.html.haml ... "
if [[ -r $OPENSHIFT_DATA_DIR/splash.html.haml ]]; then
  echo "found, copying to $OPENSHIFT_REPO_DIR/app/views/home/_show.html.haml"
  cp $OPENSHIFT_DATA_DIR/splash.html.haml $OPENSHIFT_REPO_DIR/app/views/home/_show.html.haml
else
  echo "not found -- the default splash screen will be used"
fi

REDIS_PID=$(pidof redis-server)
if [[ -z "$REDIS_PID" ]];
  echo "Starting Redis server... "
  cd $OPENSHIFT_DATA_DIR/redis/bin && ./redis-server redis.conf
else
  echo "Found Redis server running with PID $REDIS_PID"
fi


RESQUE_PIDFILE="$OPENSHIFT_DATA_DIR/redis/resque.pid"
echo -n "Checking for running Resque worker ... "
if [[ -s $RESQUE_PIDFILE ]]; then
  echo "found at $(cat $RESQUE_PIDFILE)"
else
  echo "not found, starting worker"
  cd $OPENSHIFT_REPO_DIR && bundle exec rake resque:work QUEUE="*" PIDFILE=$OPENSHIFT_DATA_DIR/redis/resque.pid BACKGROUND=yes & >> log/resque.log 2>&1
fi
