#!/bin/bash
# This script will be executed while your application is stopped
# before the build step.

STORED_ASSETS="${OPENSHIFT_DATA_DIR}assets"
LIVE_ASSETS="${OPENSHIFT_REPO_DIR}public/assets"

# Ensure our stored assets directory exists
echo -n "Checking for permanently-used assets cache at $STORED_ASSETS ... "
if [ ! -d "${STORED_ASSETS}" ]; then
  echo "not found, creating"
  mkdir "${STORED_ASSETS}"
fi

# Create symlink to stored assets unless we're uploading our own assets
echo -n "Checking for compiled assets in Git repository at $LIVE_ASSETS ... "
if [ -d "${LIVE_ASSETS}" ]; then
  echo "found -- the application will use assets stored in the Git repository !"
else
  echo "not found, using permanent cache at $STORED_ASSETS"
  ln -s "${STORED_ASSETS}" "${LIVE_ASSETS}"
fi
